version: '3.9'

services:
  web:
    build: .
    container_name: lmdjango_app
    command: gunicorn --bind 0.0.0.0:8000 --timeout 120 loanmanagement.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE = loanmanagement.settings

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/static  # Map static files volume for Nginx
    depends_on:
      - web

volumes:
  staticfiles: