# Generated by Django 5.1.6 on 2025-03-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagementapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
