# Generated by Django 5.1.6 on 2025-03-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagementapi', '0003_alter_user_created_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='monthly_installment',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_interest',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='loanmanagementapi.loan')),
            ],
        ),
    ]
