# Generated by Django 5.1.6 on 2025-03-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagementapi', '0005_loan_monthly_installment_loan_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LoanUser',
        ),
    ]
