# Generated by Django 5.1.6 on 2025-03-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('loanmanagementapi', '0006_rename_user_loanuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='loan_users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='loanuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='loanuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='loanuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='loan_users_permissions', to='auth.permission'),
        ),
    ]
