# Generated by Django 5.1.6 on 2025-04-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagementapi', '0007_loanuser_groups_loanuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='Loan',
        ),
        migrations.AlterModelTable(
            name='paymentschedule',
            table='PaymentSchedule',
        ),
    ]
